if [[ "$OSTYPE" == "darwin"* ]]; then
    brew install zsh

    brew install zsh-syntax-highlighting
    brew install zsh-autocomplete
    brew install zsh-autosuggestions
else
    apt install zsh

    mkdir -p ~/.config/zsh/plugins
    git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git ~/.config/zsh/plugins/zsh-autocomplete
    git clone --depth 1 -- https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.config/zsh/plugins/zsh-syntax-highlighting
    git clone --depth 1 -- https://github.com/zsh-users/zsh-autosuggestions.git ~/.config/zsh/plugins/zsh-autosuggestions
fi

source ~/.config/zsh/oh-my-posh/oh-my-posh.zsh