if [[ "$OSTYPE" == "darwin"* ]]; then
    brew install zsh

    brew install zsh-syntax-highlighting
    # brew install zsh-autocomplete
    brew install zsh-autosuggestions
    brew install zsh-completions
    brew install fzf-tab
else
    command -v zsh &>/dev/null || sudo apt-get install -y zsh

    mkdir -p ~/.config/zsh/plugins
    # git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git ~/.config/zsh/plugins/zsh-autocomplete
    [ -d "$HOME/.config/zsh/plugins/zsh-syntax-highlighting" ] || git clone --depth 1 -- https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.config/zsh/plugins/zsh-syntax-highlighting
    [ -d "$HOME/.config/zsh/plugins/zsh-autosuggestions" ] || git clone --depth 1 -- https://github.com/zsh-users/zsh-autosuggestions.git ~/.config/zsh/plugins/zsh-autosuggestions
    [ -d "$HOME/.config/zsh/plugins/zsh-completions" ] || git clone --depth 1 -- https://github.com/zsh-users/zsh-completions.git ~/.config/zsh/plugins/zsh-completions
    [ -d "$HOME/.config/zsh/plugins/fzf-tab" ] || git clone --depth 1 -- https://github.com/Aloxaf/fzf-tab.git ~/.config/zsh/plugins/fzf-tab
fi

source ~/.dotfiles/installers/oh-my-posh.install