if [[ "$OSTYPE" == "darwin"* ]]; then
    brew install zsh

    brew install zsh-syntax-highlighting
    # brew install zsh-autocomplete
    brew install zsh-autosuggestions
    brew install zsh-completions
    brew install fzf-tab
else
    apt install zsh

    mkdir -p ~/.config/zsh/plugins
    # git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git ~/.config/zsh/plugins/zsh-autocomplete
    git clone --depth 1 -- https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.config/zsh/plugins/zsh-syntax-highlighting
    git clone --depth 1 -- https://github.com/zsh-users/zsh-autosuggestions.git ~/.config/zsh/plugins/zsh-autosuggestions
    git clone --depth 1 -- https://github.com/zsh-users/zsh-completions.git ~/.config/zsh/plugins/zsh-completions
    git clone --depth 1 -- https://github.com/Aloxaf/fzf-tab.git ~/.config/zsh/plugins/fzf-tab
fi

source ~/.config/zsh/oh-my-posh/oh-my-posh.install